### PR TITLE
Allow passing a Document

### PR DESCRIPTION
**Pull request by ringods**
In Next.js, I have two separate functions for [generating the page metadata](https://beta.nextjs.org/docs/api-reference/metadata#generatemetadata-function) and for [rendering](https://beta.nextjs.org/docs/routing/defining-routes#creating-ui). In this setup, I want to load the content into an Asciidoc `Document` object, so I can retrieve information from it for the metadata, before I pass it to the rendering.

For this to work, I extracted the `string-to-Document` loading outside the `Asciidoc` function.

### CODE REVIEW

**Comment by ringods** [comment]
@benjaminleonard if you would have a few minutes to review and get this in a new release, that would be much appreciated.

I know this is a breaking change for you, but it also is IMO a better separation of concerns. As I indicated earlier on [your gist](https://gist.github.com/benjaminleonard/251d0271b75e89586345b9173db25fa9), my aim is to contribute further changes to make this library a [custom Asciidoc.js Converter](https://docs.asciidoctor.org/asciidoctor.js/latest/extend/converter/custom-converter/).

I hope you like the direction I'm taking with this and accept my changes. If not, let me know, because then I will have to take such implementation elsewhere.

**Comment by benjaminleonard** [comment]
Hi, thanks for the PR. In principle I like this, i'm going to test it out — and will get back to you shortly.

**Comment by benjaminleonard** [comment]
Give this a try, I was working on a way of passing attributes and extensions to the plugin but with this PR it's no longer necessary.

As a sidenote, if you're using footnotes they're broken again, not sure when or why that bug returned. I'll work on that separately.

**Comment by ringods** [comment]
With 0.0.1-alpha.20, the Typescript error is resolved for the input type to `Asciidoc`. Now I can continue integrating your lib in my setup, though that is work for this evening. Feel free to merge this PR in the meantime.

**Comment by benjaminleonard** [comment]
:rocket: PR was released in [`v0.2.5`](https://github.com/oxidecomputer/react-asciidoc/releases/tag/v0.2.5) :rocket:

**Pull request merged**
